import { useState } from 'react';
import { TrendingUp, Target, Activity, Award, Calendar } from 'lucide-react';
import { Line, Doughnut } from 'react-chartjs-2';
import PageHeader from '../../components/common/PageHeader.jsx';
import DemoNotice from '../../components/common/DemoNotice.jsx';
import StatCard from '../../components/common/StatCard.jsx';
import { mockChartData, formatCurrency } from '../../utils/mockData.js';

export default function Analytics() {
  const [period, setPeriod] = useState('8m');
  const lineData = { labels: mockChartData.portfolio.labels, datasets: [{ label: 'Portfolio Value', data: mockChartData.portfolio.data, borderColor: '#2dd4bf', backgroundColor: 'rgba(45,212,191,0.08)', fill: true, tension: 0.4, pointRadius: 3 }] };
  const doughnutData = { labels: ['Winning Trades', 'Losing Trades'], datasets: [{ data: [68, 32], backgroundColor: ['#22c55e', '#ef4444'], borderColor: '#111827', borderWidth: 3 }] };
  const lineOptions = { responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false } }, scales: { x: { grid: { display: false }, ticks: { color: '#8b949e' } }, y: { grid: { color: '#1f2a3a' }, ticks: { color: '#8b949e', callback: (v) => `$${(v / 1000).toFixed(0)}K` } } } };
  const doughnutOptions = { responsive: true, maintainAspectRatio: false, cutout: '72%', plugins: { legend: { position: 'bottom', labels: { color: '#8b949e', padding: 16 } } } };
  return <div className="tx-fade-in"><PageHeader title="Analytics" subtitle="Understand your simulated trading performance." actions={<select className="form-select form-select-sm" value={period} onChange={(e) => setPeriod(e.target.value)} style={{ width: 130 }}><option value="8m">Last 8 months</option><option value="1y">Last year</option></select>} /><DemoNotice /><div className="row g-3 mb-4"><div className="col-xl-3 col-sm-6"><StatCard title="Total Return" value="+18.96%" subtitle="Since starting" icon={TrendingUp} accent="success" /></div><div className="col-xl-3 col-sm-6"><StatCard title="Win Rate" value="68.0%" subtitle="34 of 50 trades" icon={Target} accent="primary" /></div><div className="col-xl-3 col-sm-6"><StatCard title="Total Trades" value="50" subtitle="Across 8 months" icon={Activity} accent="accent" /></div><div className="col-xl-3 col-sm-6"><StatCard title="Best Trade" value="+42.8%" subtitle="NVDA · Aug 2026" icon={Award} accent="warning" /></div></div><div className="row g-4"><div className="col-lg-8"><div className="card p-4"><div className="d-flex justify-content-between mb-4"><div><h5 className="fw-semibold mb-1" style={{ color: 'var(--tx-text)' }}>Portfolio Growth</h5><p className="mb-0" style={{ color: 'var(--tx-text-muted)', fontSize: '0.8rem' }}>Value over time</p></div><span className="d-flex align-items-center gap-1" style={{ color: 'var(--tx-text-muted)', fontSize: '0.8rem' }}><Calendar size={14} /> 2026</span></div><div style={{ height: 320 }}><Line data={lineData} options={lineOptions} /></div></div></div><div className="col-lg-4"><div className="card p-4 h-100"><h5 className="fw-semibold mb-1" style={{ color: 'var(--tx-text)' }}>Trade Outcomes</h5><p style={{ color: 'var(--tx-text-muted)', fontSize: '0.8rem' }}>Winning vs losing trades</p><div style={{ height: 260 }}><Doughnut data={doughnutData} options={doughnutOptions} /></div></div></div></div><div className="card p-4 mt-4"><h5 className="fw-semibold mb-3" style={{ color: 'var(--tx-text)' }}>Performance Summary</h5><div className="row g-4"><div className="col-md-3"><p style={{ color: 'var(--tx-text-muted)', fontSize: '0.8rem' }}>Average Win</p><p className="fw-bold text-success mb-0">+{formatCurrency(842.35)}</p></div><div className="col-md-3"><p style={{ color: 'var(--tx-text-muted)', fontSize: '0.8rem' }}>Average Loss</p><p className="fw-bold text-danger mb-0">-{formatCurrency(384.2)}</p></div><div className="col-md-3"><p style={{ color: 'var(--tx-text-muted)', fontSize: '0.8rem' }}>Profit Factor</p><p className="fw-bold mb-0" style={{ color: 'var(--tx-text)' }}>2.19</p></div><div className="col-md-3"><p style={{ color: 'var(--tx-text-muted)', fontSize: '0.8rem' }}>Largest Position</p><p className="fw-bold mb-0" style={{ color: 'var(--tx-text)' }}>NVDA · 30.2%</p></div></div></div></div>;
}
