import { Link } from 'react-router-dom';
import { DollarSign, Wallet, Briefcase, TrendingUp, ArrowUpRight, ArrowDownRight, Activity, Star, ArrowRight, BarChart3, Clock } from 'lucide-react';
import { Line } from 'react-chartjs-2';
import StatCard from '../../components/common/StatCard.jsx';
import ChangeBadge from '../../components/common/ChangeBadge.jsx';
import PageHeader from '../../components/common/PageHeader.jsx';
import DemoNotice from '../../components/common/DemoNotice.jsx';
import { mockPortfolioSummary, mockStocks, mockWatchlist, mockTransactions, mockChartData, formatCurrency, formatDate } from '../../utils/mockData.js';

const chartOptions = { responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false } }, scales: { x: { grid: { display: false }, ticks: { color: '#8b949e' } }, y: { grid: { color: '#1f2a3a' }, ticks: { color: '#8b949e', callback: (v) => `$${(v / 1000).toFixed(0)}K` } } } };

export default function Dashboard() {
  const chartData = { labels: mockChartData.portfolio.labels, datasets: [{ data: mockChartData.portfolio.data, borderColor: '#2dd4bf', backgroundColor: 'rgba(45,212,191,0.08)', fill: true, tension: 0.4, pointRadius: 0, pointHoverRadius: 5 }] };
  return <div className="tx-fade-in">
    <PageHeader title="Good morning, Trader" subtitle="Here is your portfolio overview for today." actions={<span className="tx-badge-neutral d-inline-flex align-items-center gap-1"><Activity size={13} /> Market open</span>} />
    <DemoNotice />
    <div className="row g-3 mb-4">
      <div className="col-xl-3 col-sm-6"><StatCard title="Total Portfolio Value" value={formatCurrency(mockPortfolioSummary.totalValue)} subtitle={<span className="text-success d-inline-flex align-items-center gap-1"><ArrowUpRight size={13} /> +{formatCurrency(mockPortfolioSummary.totalPnl)} today</span>} icon={DollarSign} accent="primary" /></div>
      <div className="col-xl-3 col-sm-6"><StatCard title="Available Cash" value={formatCurrency(mockPortfolioSummary.availableCash)} subtitle="Ready to invest" icon={Wallet} accent="accent" /></div>
      <div className="col-xl-3 col-sm-6"><StatCard title="Total Invested" value={formatCurrency(mockPortfolioSummary.totalInvested)} subtitle="Across 4 positions" icon={Briefcase} accent="warning" /></div>
      <div className="col-xl-3 col-sm-6"><StatCard title="Total Profit / Loss" value={`+${formatCurrency(mockPortfolioSummary.totalPnl)}`} subtitle={<span className="text-success">+{mockPortfolioSummary.totalPnlPercent}% all time</span>} icon={TrendingUp} accent="success" /></div>
    </div>
    <div className="row g-4 mb-4">
      <div className="col-lg-8"><div className="card p-4 h-100"><div className="d-flex justify-content-between align-items-center mb-3"><div><h5 className="fw-semibold mb-1" style={{ color: 'var(--tx-text)' }}>Portfolio Performance</h5><p className="mb-0" style={{ color: 'var(--tx-text-muted)', fontSize: '0.8rem' }}>Growth over the last 8 months</p></div><select className="form-select form-select-sm" style={{ width: 110 }} defaultValue="8m"><option value="8m">8 months</option><option value="1y">1 year</option></select></div><div style={{ height: 260 }}><Line data={chartData} options={chartOptions} /></div></div></div>
      <div className="col-lg-4"><div className="card p-4 h-100"><div className="d-flex justify-content-between align-items-center mb-3"><h5 className="fw-semibold mb-0" style={{ color: 'var(--tx-text)' }}>Market Overview</h5><Link to="/markets" style={{ color: 'var(--tx-primary)', fontSize: '0.8rem' }}>View all</Link></div><div className="d-flex flex-column gap-3">{mockStocks.slice(0, 5).map((stock) => <Link to={`/stocks/${stock.symbol}`} key={stock.symbol} className="d-flex justify-content-between align-items-center"><div><span className="fw-semibold" style={{ color: 'var(--tx-text)', fontSize: '0.85rem' }}>{stock.symbol}</span><span className="d-block" style={{ color: 'var(--tx-text-muted)', fontSize: '0.72rem' }}>{stock.company}</span></div><div className="text-end"><span className="d-block" style={{ color: 'var(--tx-text)', fontSize: '0.85rem' }}>{formatCurrency(stock.price)}</span><ChangeBadge value={stock.change} percent={stock.changePercent} /></div></Link>)}</div></div></div>
    </div>
    <div className="row g-4">
      <div className="col-lg-6"><div className="card p-4"><div className="d-flex justify-content-between align-items-center mb-3"><h5 className="fw-semibold mb-0" style={{ color: 'var(--tx-text)' }}>Watchlist</h5><Link to="/watchlist" style={{ color: 'var(--tx-primary)', fontSize: '0.8rem' }}>View all</Link></div><div className="table-responsive"><table className="table table-sm align-middle mb-0"><thead><tr><th>Stock</th><th>Price</th><th>Change</th></tr></thead><tbody>{mockWatchlist.slice(0, 4).map((s) => <tr key={s.symbol}><td><Link to={`/stocks/${s.symbol}`}><span className="fw-semibold" style={{ color: 'var(--tx-text)' }}>{s.symbol}</span><span className="d-block" style={{ color: 'var(--tx-text-muted)', fontSize: '0.72rem' }}>{s.company}</span></Link></td><td style={{ color: 'var(--tx-text)' }}>{formatCurrency(s.price)}</td><td><ChangeBadge value={s.change} percent={s.changePercent} /></td></tr>)}</tbody></table></div></div></div>
      <div className="col-lg-6"><div className="card p-4"><div className="d-flex justify-content-between align-items-center mb-3"><h5 className="fw-semibold mb-0" style={{ color: 'var(--tx-text)' }}>Recent Transactions</h5><Link to="/transactions" style={{ color: 'var(--tx-primary)', fontSize: '0.8rem' }}>View all</Link></div><div className="d-flex flex-column gap-2">{mockTransactions.slice(0, 4).map((tx) => <div key={tx.id} className="d-flex justify-content-between align-items-center py-2"><div className="d-flex align-items-center gap-2"><div className="d-flex align-items-center justify-content-center rounded-3" style={{ width: 32, height: 32, backgroundColor: tx.type === 'buy' ? 'rgba(34,197,94,0.12)' : 'rgba(239,68,68,0.12)' }}>{tx.type === 'buy' ? <ArrowDownRight size={16} className="text-success" /> : <ArrowUpRight size={16} className="text-danger" />}</div><div><p className="mb-0 fw-semibold" style={{ color: 'var(--tx-text)', fontSize: '0.85rem' }}>{tx.type === 'buy' ? 'Bought' : 'Sold'} {tx.symbol}</p><p className="mb-0" style={{ color: 'var(--tx-text-muted)', fontSize: '0.72rem' }}>{formatDate(tx.date)}</p></div></div><div className="text-end"><p className="mb-0 fw-semibold" style={{ color: 'var(--tx-text)', fontSize: '0.85rem' }}>{formatCurrency(tx.total)}</p><p className="mb-0 text-uppercase" style={{ color: tx.type === 'buy' ? 'var(--tx-success)' : 'var(--tx-danger)', fontSize: '0.68rem' }}>{tx.type}</p></div></div>)}</div></div></div>
    </div>
  </div>;
}
