import { Briefcase, TrendingUp, DollarSign, PieChart as PieChartIcon } from 'lucide-react';
import { Pie } from 'react-chartjs-2';
import PageHeader from '../../components/common/PageHeader.jsx';
import DemoNotice from '../../components/common/DemoNotice.jsx';
import StatCard from '../../components/common/StatCard.jsx';
import ChangeBadge from '../../components/common/ChangeBadge.jsx';
import { mockHoldings, mockPortfolioSummary, formatCurrency } from '../../utils/mockData.js';

export default function Portfolio() {
  const pieData = { labels: mockHoldings.map((h) => h.symbol), datasets: [{ data: mockHoldings.map((h) => h.value), backgroundColor: ['#2dd4bf', '#3b82f6', '#f59e0b', '#ef4444'], borderColor: '#111827', borderWidth: 3 }] };
  const pieOptions = { responsive: true, maintainAspectRatio: false, plugins: { legend: { position: 'bottom', labels: { color: '#8b949e', padding: 16 } } } };
  return <div className="tx-fade-in"><PageHeader title="Portfolio" subtitle="Track your holdings and simulated performance." /><DemoNotice /><div className="row g-3 mb-4"><div className="col-lg-3 col-sm-6"><StatCard title="Portfolio Value" value={formatCurrency(mockPortfolioSummary.totalValue)} icon={DollarSign} /></div><div className="col-lg-3 col-sm-6"><StatCard title="Invested" value={formatCurrency(mockPortfolioSummary.totalInvested)} icon={Briefcase} accent="warning" /></div><div className="col-lg-3 col-sm-6"><StatCard title="Total P/L" value={`+${formatCurrency(mockPortfolioSummary.totalPnl)}`} subtitle={`+${mockPortfolioSummary.totalPnlPercent}% return`} icon={TrendingUp} accent="success" /></div><div className="col-lg-3 col-sm-6"><StatCard title="Positions" value={mockHoldings.length} subtitle="Active holdings" icon={PieChartIcon} accent="accent" /></div></div><div className="row g-4"><div className="col-lg-8"><div className="card p-4"><h5 className="fw-semibold mb-3" style={{ color: 'var(--tx-text)' }}>Your Holdings</h5><div className="table-responsive"><table className="table table-hover align-middle"><thead><tr><th>Asset</th><th>Shares</th><th>Avg. Price</th><th>Current Price</th><th>Market Value</th><th>P/L</th></tr></thead><tbody>{mockHoldings.map((h) => <tr key={h.symbol}><td><span className="fw-bold" style={{ color: 'var(--tx-text)' }}>{h.symbol}</span><span className="d-block" style={{ color: 'var(--tx-text-muted)', fontSize: '0.75rem' }}>{h.company}</span></td><td style={{ color: 'var(--tx-text)' }}>{h.shares}</td><td style={{ color: 'var(--tx-text)' }}>{formatCurrency(h.avgPrice)}</td><td style={{ color: 'var(--tx-text)' }}>{formatCurrency(h.currentPrice)}</td><td className="fw-semibold" style={{ color: 'var(--tx-text)' }}>{formatCurrency(h.value)}</td><td><ChangeBadge value={h.pnl} percent={h.pnlPercent} /></td></tr>)}</tbody></table></div></div></div><div className="col-lg-4"><div className="card p-4 h-100"><h5 className="fw-semibold mb-3" style={{ color: 'var(--tx-text)' }}>Allocation</h5><div style={{ height: 280 }}><Pie data={pieData} options={pieOptions} /></div></div></div></div></div>;
}
