import { useState } from 'react';
import { ArrowDownRight, ArrowUpRight, Download, Filter } from 'lucide-react';
import PageHeader from '../../components/common/PageHeader.jsx';
import DemoNotice from '../../components/common/DemoNotice.jsx';
import { mockTransactions, formatCurrency, formatDate } from '../../utils/mockData.js';

export default function Transactions() {
  const [filter, setFilter] = useState('all');
  const rows = filter === 'all' ? mockTransactions : mockTransactions.filter((t) => t.type === filter);
  return <div className="tx-fade-in"><PageHeader title="Transactions" subtitle="Review your simulated trading activity." actions={<button className="btn btn-outline-primary d-flex align-items-center gap-2"><Download size={16} /> Export</button>} /><DemoNotice /><div className="card p-3 p-md-4"><div className="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-3 mb-4"><div><h5 className="fw-semibold mb-1" style={{ color: 'var(--tx-text)' }}>Transaction History</h5><p className="mb-0" style={{ color: 'var(--tx-text-muted)', fontSize: '0.82rem' }}>All buys and sells in your paper account</p></div><div className="d-flex gap-2"><button className={`btn btn-sm ${filter === 'all' ? 'btn-primary' : 'btn-outline-primary'}`} onClick={() => setFilter('all')}>All</button><button className={`btn btn-sm ${filter === 'buy' ? 'btn-primary' : 'btn-outline-primary'}`} onClick={() => setFilter('buy')}>Buys</button><button className={`btn btn-sm ${filter === 'sell' ? 'btn-primary' : 'btn-outline-primary'}`} onClick={() => setFilter('sell')}>Sells</button><button className="btn btn-sm btn-outline-primary"><Filter size={14} /></button></div></div><div className="table-responsive"><table className="table table-hover align-middle"><thead><tr><th>Type</th><th>Symbol</th><th>Shares</th><th>Price</th><th>Total</th><th>Date</th><th>Status</th></tr></thead><tbody>{rows.map((tx) => <tr key={tx.id}><td><span className={`d-inline-flex align-items-center gap-1 ${tx.type === 'buy' ? 'tx-badge-up' : 'tx-badge-down'}`}>{tx.type === 'buy' ? <ArrowDownRight size={13} /> : <ArrowUpRight size={13} />}{tx.type.toUpperCase()}</span></td><td className="fw-bold" style={{ color: 'var(--tx-text)' }}>{tx.symbol}</td><td style={{ color: 'var(--tx-text)' }}>{tx.shares}</td><td style={{ color: 'var(--tx-text)' }}>{formatCurrency(tx.price)}</td><td className="fw-semibold" style={{ color: 'var(--tx-text)' }}>{formatCurrency(tx.total)}</td><td style={{ color: 'var(--tx-text-muted)', fontSize: '0.82rem' }}>{formatDate(tx.date)}</td><td><span className="tx-badge-up">{tx.status}</span></td></tr>)}</tbody></table></div></div></div>;
}
